spring.application.name=vivaeventos-order-service
server.port=8083

# URL del event-service
services.event-service.url=http://localhost:8082

# Base de datos del order-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/order-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Tests
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop